package com.trianguloy.generator.custom

import com.trianguloy.generator.wff.WatchFace
import com.trianguloy.generator.xml.Comment
import java.io.File


fun WatchFace.toProject() {
    File("watchface/src/main/res/raw", "watchface.xml")
        .writeText(
            """
                ${Comment("Generated by TrianguloY watchface tool")}
                $this
            """.trimIndent()
        )
}